on:
  workflow_call: 
    inputs:
      backend-url:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest        

    steps:
      - name: mensagem
        run: echo backend address ====> ${{inputs.backend-url}}